package cz.velim.hibernatetest.entities;

// Generated Aug 4, 2013 11:10:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Test generated by hbm2java
 */
@SuppressWarnings("serial")
public class Names implements java.io.Serializable {

	private Integer id;
	private String name;

	public Names() {
	}

	public Names(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
